[package]
name = "rusty-bolt"
version = "0.1.0"
authors = ["Nigel Small <nigel@nigelsmall.name>"]

[dependencies]
log = "0.3.7"
cypherstream = { path = "cypherstream" }
boltstream = { path = "boltstream" }
packstream = { path = "packstream" }
